[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "server"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/api/:splat"


